In [17]:
import sqlite3
from sqlite3 import Error

 
def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn

 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """
        SELECT *
        FROM FACILITIES
        """
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)


def main():
    database = "sqlite_db_pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
2. Query all tasks
(0, 'Tennis Court 1', 5, 25, 10000, 200)
(1, 'Tennis Court 2', 5, 25, 8000, 200)
(2, 'Badminton Court', 0, 15.5, 4000, 50)
(3, 'Table Tennis', 0, 5, 320, 10)
(4, 'Massage Room 1', 9.9, 80, 4000, 3000)
(5, 'Massage Room 2', 9.9, 80, 4000, 3000)
(6, 'Squash Court', 3.5, 17.5, 5000, 80)
(7, 'Snooker Table', 0, 5, 450, 15)
(8, 'Pool Table', 0, 5, 400, 15)

In [15]:
/* Q10: Produce a list of facilities with a total revenue less than 1000.
The output of facility name and total revenue, sorted by revenue. Remember
that theres a different cost for guests and members! */

SyntaxError: invalid syntax (<ipython-input-15-50415e63d49f>, line 1)

In [22]:
def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn

 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """
        SELECT f.name AS facility_name,
          SUM(CASE WHEN m.memid = 0 THEN (guestcost * slots)
            ELSE (membercost * slots) END) AS revenue
        FROM Bookings as b
        LEFT JOIN Members as m
        ON m.memid = b.memid
        LEFT JOIN Facilities as f
        ON f.facid = b.facid
        GROUP BY facility_name
        HAVING revenue < 1000
        ORDER BY revenue DESC;
        """
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)


def main():
    database = "sqlite_db_pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
2. Query all tasks
('Pool Table', 270)
('Snooker Table', 240)
('Table Tennis', 180)

In [ ]:
/* Q11: Produce a report of members and who recommended them in alphabetic surname,firstname order */

In [24]:
def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn

 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """
            SELECT m1.surname || " " || m1.firstname AS Member_Name,
              m2.surname || " " || m2.firstname AS Recommended_By
            FROM Members AS m1
            INNER JOIN Members AS m2
            ON m1.recommendedby = m2.memid
            WHERE m1.recommendedby IS NOT NULL AND m1.recommendedby <> 0
            ORDER BY Member_Name;
            """
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)


def main():
    database = "sqlite_db_pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
2. Query all tasks
('Bader Florence', 'Stibbons Ponder')
('Baker Anne', 'Stibbons Ponder')
('Baker Timothy', 'Farrell Jemima')
('Boothe Tim', 'Rownam Tim')
('Butters Gerald', 'Smith Darren')
('Coplin Joan', 'Baker Timothy')
('Crumpet Erica', 'Smith Tracy')
('Dare Nancy', 'Joplette Janice')
('Genting Matthew', 'Butters Gerald')
('Hunt John', 'Purview Millicent')
('Jones David', 'Joplette Janice')
('Jones Douglas', 'Jones David')
('Joplette Janice', 'Smith Darren')
('Mackenzie Anna', 'Smith Darren')
('Owen Charles', 'Smith Darren')
('Pinker David', 'Farrell Jemima')
('Purview Millicent', 'Smith Tracy')
('Rumney Henrietta', 'Genting Matthew')
('Sarwin Ramnaresh', 'Bader Florence')
('Smith Jack', 'Smith Darren')
('Stibbons Ponder', 'Tracy Burton')
('Worthington-Smyth Henry', 'Smith Tracy')

In [ ]:
/* Q12: Find the facilities with their usage by member, but not guests */

In [27]:
def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn

 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """
            SELECT f.name AS Facility_Name,
            SUM(SLOTS) AS Total_Usage
            FROM Bookings as b
            LEFT JOIN Facilities as f
            ON f.facid = b.facid
            WHERE b.memid > 0
            GROUP BY Facility_Name
            ORDER BY Total_Usage DESC;
            """
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)


def main():
    database = "sqlite_db_pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
2. Query all tasks
('Badminton Court', 1086)
('Tennis Court 1', 957)
('Massage Room 1', 884)
('Tennis Court 2', 882)
('Snooker Table', 860)
('Pool Table', 856)
('Table Tennis', 794)
('Squash Court', 418)
('Massage Room 2', 54)

In [ ]:
/* Q13: Find the facilities usage by month, but not guests */

In [28]:
def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn

 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """
            SELECT f.name AS Facility_Name,
              strftime('%,m', starttime) AS Month,
              SUM(slots) AS Total_Usage
            FROM Bookings as b
            LEFT JOIN Facilities as f
            ON f.facid = b.facid
            WHERE b.memid > 0
            GROUP BY Facility_Name, Month;
            """
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)


def main():
    database = "sqlite_db_pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
2. Query all tasks
('Badminton Court', None, 1086)
('Massage Room 1', None, 884)
('Massage Room 2', None, 54)
('Pool Table', None, 856)
('Snooker Table', None, 860)
('Squash Court', None, 418)
('Table Tennis', None, 794)
('Tennis Court 1', None, 957)
('Tennis Court 2', None, 882)